// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderInventory.Infrastructure.Persistence;

#nullable disable

namespace OrderInventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderInventoryDbContext))]
    [Migration("20260824163000_AddStockMovements")]
    partial class AddStockMovements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderInventory.Core.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("OnHandStock")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand_stock");

                    b.Property<int>("ReservedStock")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_stock");

                    b.HasKey("ProductId");

                    b.ToTable("inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_items_on_hand_stock_non_negative", "on_hand_stock >= 0");

                            t.HasCheckConstraint("ck_inventory_items_reserved_stock_non_negative", "reserved_stock >= 0");

                            t.HasCheckConstraint("ck_inventory_items_reserved_stock_not_above_on_hand", "reserved_stock <= on_hand_stock");
                        });
                });

            modelBuilder.Entity("OrderInventory.Core.Inventory.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "OccurredAtUtc");

                    b.ToTable("stock_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_movements_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("OrderInventory.Core.Inventory.StockMovement", b =>
                {
                    b.HasOne("OrderInventory.Core.Inventory.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
